name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  easy_ads_flutter: ^2.1.0
  easy_prank_call:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/videos/