name: easy_prank_call
description: You can schedule a prank audio and video call with this package.
version: 2.1.0
repository: https://github.com/nooralibutt/easy_prank_call
homepage: https://github.com/nooralibutt/easy_prank_call

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.3
  just_audio: ^0.9.31
  flutter_spinkit: ^5.1.0
  video_player: ^2.5.1
  vibration: ^1.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/audio/
